AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:

  Function:
    FunctionUrlConfig:
      AuthType: NONE
    Runtime: java11

  Resources:
    MainFunctionQuarkus:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: target/function.zip
        MemorySize: 512
        Timeout: 30
        Policies:
          - AWSLambdaBasicExecutionRole
          - AmazonDynamoDBFullAccess
          - CloudWatchLogsFullAccess
        Environment:
          Variables:
            TABLE_NAME: serverless2049-dynamodb-table-Database

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: serverless2049-dynamodb-table-Database
      PrimaryKey:
        Name: id
        Type: String